### ISSUE TITLE
what is boundarysrc in poisson_reconstruct2

### ISSUE THREAD

**Issue by wyj2046** [rohitrango/automatic-watermark-detection#2]
Hi, rohitrango
After read your code, i wonder this function: poisson_reconstruct2, the parameter boundarysrc means, is that the watermarks img?
Give a example to use this function is appreciate, thank you!

**Comment by rohitrango** [comment]
There's a different variant of poisson reconstruction which has the additional information about the boundary pixels of the source image. A matrix of the size of the source image is passed and only the boundary pixels of the

**Comment by rohitrango** [comment]
*image is used.
